/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.ControladorMaquina;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import modelo.Maquina;

/**
 *
 * @author juanjoanduquia
 */
public class VistaGestionMaquina extends javax.swing.JFrame {

    ControladorMaquina controladorMaquina;

    /**
     * Creates new form VistaGestionMaquina
     */
    public VistaGestionMaquina() {
        initComponents();
        setLocationRelativeTo(this);
        this.controladorMaquina = new ControladorMaquina();
        llenarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIdMaquina = new javax.swing.JLabel();
        txtIdMaquina = new javax.swing.JTextField();
        lblEdadMinima = new javax.swing.JLabel();
        txtEdadMinima = new javax.swing.JTextField();
        lblTipoDeJuego = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblValorHora = new javax.swing.JLabel();
        txtTipoDeJuego = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtValorHora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMaquina = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnMantenimiento = new javax.swing.JButton();
        jCheckBoxFueraDeServicio = new javax.swing.JCheckBox();
        btnRegresarAvistaAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestión De Maquinas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 18))); // NOI18N
        jPanel1.setToolTipText("");

        lblIdMaquina.setText("Id maquina:");

        lblEdadMinima.setText("Edad minima:");

        lblTipoDeJuego.setText("Tipo de juego:");

        lblGenero.setText("Genero:");

        lblValorHora.setText("Valor Hora:");

        tablaMaquina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMaquina);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnMantenimiento.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnMantenimiento.setText("DESACTIVAR MAQUINA");
        btnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoActionPerformed(evt);
            }
        });

        jCheckBoxFueraDeServicio.setText("Fuera De Servicio");

        btnRegresarAvistaAdmin.setText("🔙");
        btnRegresarAvistaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarAvistaAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdMaquina)
                                    .addComponent(lblEdadMinima)
                                    .addComponent(lblTipoDeJuego)
                                    .addComponent(lblGenero)
                                    .addComponent(lblValorHora))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdMaquina)
                                    .addComponent(txtEdadMinima)
                                    .addComponent(txtTipoDeJuego)
                                    .addComponent(txtGenero)
                                    .addComponent(txtValorHora)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxFueraDeServicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMantenimiento)
                    .addComponent(btnRegresarAvistaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdMaquina)
                            .addComponent(txtIdMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEdadMinima)
                            .addComponent(txtEdadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoDeJuego)
                            .addComponent(txtTipoDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGenero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorHora)
                            .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxFueraDeServicio))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMantenimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnRegresarAvistaAdmin))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        int idMaquina = Integer.parseInt(txtIdMaquina.getText());
        int edadMinima = Integer.parseInt(txtEdadMinima.getText());
        String tipoJuego = txtTipoDeJuego.getText();
        String genero = txtGenero.getText();
        double valorHora = Double.valueOf(txtValorHora.getText());
        boolean disponible = jCheckBoxFueraDeServicio.isSelected();
        Maquina maquina = new Maquina(idMaquina, edadMinima, tipoJuego, genero, valorHora, disponible);
        boolean respuesta = controladorMaquina.guardarMaquina(maquina);
        if (respuesta) {
            JOptionPane.showMessageDialog(null, "Se guardo");
            llenarTabla();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(null, "No se guardo");

        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        int idMaquina = Integer.parseInt(txtIdMaquina.getText());
        Maquina respuesta = controladorMaquina.buscarMaquina(idMaquina);
        if (respuesta != null) {
            txtEdadMinima.setText(String.valueOf(respuesta.getEdadMinima()));
            txtTipoDeJuego.setText(respuesta.getTipoDeJuego());
            txtGenero.setText(respuesta.getGenero());
            txtValorHora.setText(String.valueOf(respuesta.getValorHora()));
            JOptionPane.showMessageDialog(null, "Se encontro");

        } else {
            JOptionPane.showMessageDialog(null, "No se encontro");

        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int idMaquina = Integer.parseInt(txtIdMaquina.getText());
        int edadMinima = Integer.parseInt(txtEdadMinima.getText());
        String tipoJuego = txtTipoDeJuego.getText();
        String genero = txtGenero.getText();
        double valorHora = Double.valueOf(txtValorHora.getText());
        boolean disponible = jCheckBoxFueraDeServicio.isSelected();
        Maquina maquina = new Maquina(idMaquina, edadMinima, tipoJuego, genero, valorHora, disponible);
        boolean respuesta = controladorMaquina.editarMaquina(maquina);
        if (respuesta) {
            JOptionPane.showMessageDialog(null, "Se edito");
            llenarTabla();
            limpiarCampos();

        } else {
            JOptionPane.showMessageDialog(null, "No se edito");

        }


    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int idMaquina = Integer.parseInt(txtIdMaquina.getText());
        boolean respuesta = controladorMaquina.eliminarMaquina(idMaquina);
        if (respuesta) {
            JOptionPane.showMessageDialog(null, "Se elimino");
            llenarTabla();
            limpiarCampos();

        } else {
            JOptionPane.showMessageDialog(null, "No se edito");

        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoActionPerformed
        // TODO add your handling code here:
        VistaMantenimiento vistaM = new VistaMantenimiento();
        vistaM.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnMantenimientoActionPerformed

    private void btnRegresarAvistaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarAvistaAdminActionPerformed
        // TODO add your handling code here:
        VistaAdministrador vistaAdministrador = new VistaAdministrador();
        vistaAdministrador.setVisible(true);
        vistaAdministrador.setLocationRelativeTo(this);
        this.dispose();

    }//GEN-LAST:event_btnRegresarAvistaAdminActionPerformed

    public void limpiarCampos() {
        txtIdMaquina.setText(null);
        txtEdadMinima.setText(null);
        txtTipoDeJuego.setText(null);
        txtGenero.setText(null);
        txtValorHora.setText(null);
    }

    public void llenarTabla() {
        tablaMaquina.setModel(controladorMaquina.listarMaquina());
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMantenimiento;
    private javax.swing.JButton btnRegresarAvistaAdmin;
    private javax.swing.JCheckBox jCheckBoxFueraDeServicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEdadMinima;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblIdMaquina;
    private javax.swing.JLabel lblTipoDeJuego;
    private javax.swing.JLabel lblValorHora;
    private javax.swing.JTable tablaMaquina;
    private javax.swing.JTextField txtEdadMinima;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtIdMaquina;
    private javax.swing.JTextField txtTipoDeJuego;
    private javax.swing.JTextField txtValorHora;
    // End of variables declaration//GEN-END:variables
}
