/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.ControladorMantenimiento;
import controlador.ControladorMaquina;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import modelo.Mantenimiento;
import modelo.Maquina;

/**
 *
 * @author juanjoanduquia
 */
public class VistaGestionMaquina extends javax.swing.JFrame {

    ControladorMaquina controladorMaquina;
    ControladorMantenimiento controladorMantenimiento;

    /**
     * Creates new form VistaGestionMaquina
     */
    public VistaGestionMaquina() {
        initComponents();
        setLocationRelativeTo(this);
        this.controladorMaquina = new ControladorMaquina();
        this.controladorMantenimiento = new ControladorMantenimiento();
        llenarTabla();
        panelMantenimiento.setVisible(false);
        panelMotivo.setVisible(false);
        jCheckBoxFueraDeServicio.setVisible(false);
        txtFechaInicio.setText(LocalDate.now().toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIdMaquina = new javax.swing.JLabel();
        txtIdMaquina = new javax.swing.JTextField();
        lblEdadMinima = new javax.swing.JLabel();
        txtEdadMinima = new javax.swing.JTextField();
        lblTipoDeJuego = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblValorHora = new javax.swing.JLabel();
        txtTipoDeJuego = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtValorHora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMaquina = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnMantenimiento = new javax.swing.JButton();
        jCheckBoxFueraDeServicio = new javax.swing.JCheckBox();
        btnRegresarAvistaAdmin = new javax.swing.JButton();
        panelMantenimiento = new javax.swing.JPanel();
        lblMotivo = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        lblDiasRestante = new javax.swing.JLabel();
        txtDiasRestante = new javax.swing.JTextField();
        btnGeneralBloqueo = new javax.swing.JButton();
        btnEliminarBloqueo = new javax.swing.JButton();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        panelMotivo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaBloqueo = new javax.swing.JTable();
        btnVerMotivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestión De Maquinas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 18))); // NOI18N
        jPanel1.setToolTipText("");

        lblIdMaquina.setText("Id maquina:");

        lblEdadMinima.setText("Edad minima:");

        lblTipoDeJuego.setText("Tipo de juego:");

        lblGenero.setText("Genero:");

        lblValorHora.setText("Valor Hora:");

        tablaMaquina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMaquina);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnMantenimiento.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnMantenimiento.setText("DESACTIVAR MAQUINA");
        btnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoActionPerformed(evt);
            }
        });

        jCheckBoxFueraDeServicio.setText("Fuera De Servicio");

        btnRegresarAvistaAdmin.setText("🔙");
        btnRegresarAvistaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarAvistaAdminActionPerformed(evt);
            }
        });

        panelMantenimiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mantenimiento", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 18))); // NOI18N

        lblMotivo.setText("Motivo:");

        lblFechaInicio.setText("Fecha de inicio:");

        lblFechaFin.setText("Fecha de fin:");

        lblDiasRestante.setText("Dias restante:");

        txtDiasRestante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiasRestanteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiasRestanteKeyTyped(evt);
            }
        });

        btnGeneralBloqueo.setText("Generar Bloqueo");
        btnGeneralBloqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralBloqueoActionPerformed(evt);
            }
        });

        btnEliminarBloqueo.setText("Eliminar bloqueo");
        btnEliminarBloqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBloqueoActionPerformed(evt);
            }
        });

        txtFechaInicio.setEditable(false);

        txtFechaFin.setEditable(false);

        javax.swing.GroupLayout panelMantenimientoLayout = new javax.swing.GroupLayout(panelMantenimiento);
        panelMantenimiento.setLayout(panelMantenimientoLayout);
        panelMantenimientoLayout.setHorizontalGroup(
            panelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMantenimientoLayout.createSequentialGroup()
                        .addGroup(panelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaFin)
                            .addComponent(lblFechaInicio)
                            .addComponent(lblMotivo)
                            .addComponent(lblDiasRestante))
                        .addGap(12, 12, 12)
                        .addGroup(panelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txtDiasRestante, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txtFechaInicio)
                            .addComponent(txtFechaFin)))
                    .addGroup(panelMantenimientoLayout.createSequentialGroup()
                        .addComponent(btnGeneralBloqueo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarBloqueo)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelMantenimientoLayout.setVerticalGroup(
            panelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantenimientoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMantenimientoLayout.createSequentialGroup()
                        .addComponent(lblMotivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaInicio)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMantenimientoLayout.createSequentialGroup()
                        .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaFin)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiasRestante)
                    .addComponent(txtDiasRestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGeneralBloqueo)
                    .addComponent(btnEliminarBloqueo))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        panelMotivo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Motivos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 12))); // NOI18N

        tablaBloqueo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaBloqueo);

        javax.swing.GroupLayout panelMotivoLayout = new javax.swing.GroupLayout(panelMotivo);
        panelMotivo.setLayout(panelMotivoLayout);
        panelMotivoLayout.setHorizontalGroup(
            panelMotivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMotivoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        panelMotivoLayout.setVerticalGroup(
            panelMotivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMotivoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        btnVerMotivo.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnVerMotivo.setText("VER MOTIVO");
        btnVerMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMotivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdMaquina)
                                    .addComponent(lblEdadMinima)
                                    .addComponent(lblTipoDeJuego)
                                    .addComponent(lblGenero)
                                    .addComponent(lblValorHora))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtGenero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(txtTipoDeJuego, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEdadMinima, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdMaquina, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorHora)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar))
                            .addComponent(jCheckBoxFueraDeServicio)))
                    .addComponent(btnMantenimiento)
                    .addComponent(panelMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresarAvistaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdMaquina)
                            .addComponent(txtIdMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEdadMinima)
                            .addComponent(txtEdadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoDeJuego)
                            .addComponent(txtTipoDeJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGenero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorHora)
                            .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxFueraDeServicio))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnGuardar)
                                .addComponent(btnBuscar))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnEditar)
                                .addComponent(btnEliminar))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnVerMotivo)
                            .addGap(10, 10, 10)
                            .addComponent(panelMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)))
                .addGap(8, 8, 8)
                .addComponent(btnRegresarAvistaAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 897, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        int idMaquina = Integer.parseInt(txtIdMaquina.getText());
        int edadMinima = Integer.parseInt(txtEdadMinima.getText());
        String tipoJuego = txtTipoDeJuego.getText();
        String genero = txtGenero.getText();
        double valorHora = Double.valueOf(txtValorHora.getText());
        boolean disponible = jCheckBoxFueraDeServicio.isSelected();
        Maquina maquina = new Maquina(idMaquina, edadMinima, tipoJuego, genero, valorHora, disponible);
        boolean respuesta = controladorMaquina.guardarMaquina(maquina);
        if (respuesta) {
            JOptionPane.showMessageDialog(null, "Se guardo");
            llenarTabla();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(null, "No se guardo");

        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        int idMaquina = Integer.parseInt(txtIdMaquina.getText());
        Maquina respuesta = controladorMaquina.buscarMaquina(idMaquina);
        if (respuesta != null) {
            txtEdadMinima.setText(String.valueOf(respuesta.getEdadMinima()));
            txtTipoDeJuego.setText(respuesta.getTipoDeJuego());
            txtGenero.setText(respuesta.getGenero());
            txtValorHora.setText(String.valueOf(respuesta.getValorHora()));
            JOptionPane.showMessageDialog(null, "Se encontro");

        } else {
            JOptionPane.showMessageDialog(null, "No se encontro");

        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int idMaquina = Integer.parseInt(txtIdMaquina.getText());
        int edadMinima = Integer.parseInt(txtEdadMinima.getText());
        String tipoJuego = txtTipoDeJuego.getText();
        String genero = txtGenero.getText();
        double valorHora = Double.valueOf(txtValorHora.getText());
        boolean disponible = jCheckBoxFueraDeServicio.isSelected();
        Maquina maquina = new Maquina(idMaquina, edadMinima, tipoJuego, genero, valorHora, disponible);
        boolean respuesta = controladorMaquina.editarMaquina(maquina);
        if (respuesta) {
            JOptionPane.showMessageDialog(null, "Se edito");
            llenarTabla();
            limpiarCampos();

        } else {
            JOptionPane.showMessageDialog(null, "No se edito");

        }


    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int idMaquina = Integer.parseInt(txtIdMaquina.getText());
        boolean respuesta = controladorMaquina.eliminarMaquina(idMaquina);
        if (respuesta) {
            JOptionPane.showMessageDialog(null, "Se elimino");
            llenarTabla();
            limpiarCampos();

        } else {
            JOptionPane.showMessageDialog(null, "No se edito");

        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoActionPerformed
        // TODO add your handling code here:
        panelMantenimiento.setVisible(true);
    }//GEN-LAST:event_btnMantenimientoActionPerformed

    private void btnRegresarAvistaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarAvistaAdminActionPerformed
        // TODO add your handling code here:
        VistaAdministrador vistaAdministrador = new VistaAdministrador();
        vistaAdministrador.setVisible(true);
        vistaAdministrador.setLocationRelativeTo(this);
        this.dispose();

    }//GEN-LAST:event_btnRegresarAvistaAdminActionPerformed

    private void btnGeneralBloqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralBloqueoActionPerformed
        // TODO add your handling code here:
        String motivo = txtMotivo.getText();
        LocalDateTime fechaInicio = LocalDateTime.now();
        int diasRestantes = Integer.parseInt(txtDiasRestante.getText());
        int idMaquina = Integer.parseInt(txtIdMaquina.getText());
        int edadMinima = Integer.parseInt(txtEdadMinima.getText());
        String tipoJuego = txtTipoDeJuego.getText();
        String genero = txtGenero.getText();
        double valorHora = Double.valueOf(txtValorHora.getText());
        boolean disponible = jCheckBoxFueraDeServicio.isSelected();
        Maquina maquina = new Maquina(idMaquina, edadMinima, tipoJuego, genero, valorHora, disponible);
        Mantenimiento mantenimiento = new Mantenimiento(motivo, fechaInicio, maquina, diasRestantes);
        boolean respuesta = controladorMantenimiento.generarBloqueo(maquina, mantenimiento);
        if (respuesta) {
            JOptionPane.showMessageDialog(null, "Se bloqueo la maquina");
            llenarTabla();
            limpiarCampos();

        } else {
            JOptionPane.showMessageDialog(null, "No se bloqueo la maquina");

        }
    }//GEN-LAST:event_btnGeneralBloqueoActionPerformed

    private void btnEliminarBloqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBloqueoActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdMaquina.getText());
        boolean respuesta = controladorMantenimiento.eliminarBloqueo(id);
        if (respuesta) {
            JOptionPane.showMessageDialog(null, "Se elimino el bloqueo, ahora la maquina esta disponible");
            llenarTabla();

            limpiarCampos();

        } else {
            JOptionPane.showMessageDialog(null, "No se encontro la maquina o la maquina no tiene un bloqueo");

        }

    }//GEN-LAST:event_btnEliminarBloqueoActionPerformed

    private void btnVerMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMotivoActionPerformed
        // TODO add your handling code here:
        panelMotivo.setVisible(true);
    }//GEN-LAST:event_btnVerMotivoActionPerformed

    private void txtDiasRestanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiasRestanteKeyTyped
        // TODO add your handling code here:
        

    }//GEN-LAST:event_txtDiasRestanteKeyTyped

    private void txtDiasRestanteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiasRestanteKeyReleased
        // TODO add your handling code here:
        if (!txtDiasRestante.getText().isEmpty()) {
            LocalDate fechafin = LocalDate.now().plusDays(Integer.parseInt(txtDiasRestante.getText()));
            txtFechaFin.setText(fechafin.toString());
        }
    }//GEN-LAST:event_txtDiasRestanteKeyReleased

    public void limpiarCampos() {
        txtIdMaquina.setText(null);
        txtEdadMinima.setText(null);
        txtTipoDeJuego.setText(null);
        txtGenero.setText(null);
        txtValorHora.setText(null);
    }

    public void llenarTabla() {
        tablaMaquina.setModel(controladorMaquina.listarMaquina());
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarBloqueo;
    private javax.swing.JButton btnGeneralBloqueo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMantenimiento;
    private javax.swing.JButton btnRegresarAvistaAdmin;
    private javax.swing.JButton btnVerMotivo;
    private javax.swing.JCheckBox jCheckBoxFueraDeServicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDiasRestante;
    private javax.swing.JLabel lblEdadMinima;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblIdMaquina;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblTipoDeJuego;
    private javax.swing.JLabel lblValorHora;
    private javax.swing.JPanel panelMantenimiento;
    private javax.swing.JPanel panelMotivo;
    private javax.swing.JTable tablaBloqueo;
    private javax.swing.JTable tablaMaquina;
    private javax.swing.JTextField txtDiasRestante;
    private javax.swing.JTextField txtEdadMinima;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtIdMaquina;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtTipoDeJuego;
    private javax.swing.JTextField txtValorHora;
    // End of variables declaration//GEN-END:variables
}
